name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        uses: actions/checkout@v1
        run: echo running on branche ${GITHUB_REF##*/}

      - name: Run Docker
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Eduardo"