name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      -
        name: Git checkout
        uses: actions/checkout@v2

      -
        name: Extract branch name
        run: echo running on branche ${GITHUB_REF##*/}

      -
        name: Build
        uses: ./action-a
        with:
          MY_NAME: "Eduardo"